using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using AutoLog.Infrastructure.Data;
using AutoLog.Domain.Entities;
using AutoLog.Domain.Exceptions;

namespace AutoLog.API.Middlewares;

/// <summary>
/// Global handler to catch exceptions, log them to the database,
/// and return a standardized JSON response for the frontend.
/// </summary>
public class GlobalExceptionHandler(
    ILogger<GlobalExceptionHandler> logger) : IExceptionHandler
{
    public async ValueTask<bool> TryHandleAsync(
        HttpContext httpContext, 
        Exception exception, 
        CancellationToken cancellationToken)
    {
        var incidentNumber = Guid.NewGuid();
        var errorCode = "e00000"; // Default code for unhandled exceptions
        var statusCode = StatusCodes.Status500InternalServerError;

        var dbContext = httpContext.RequestServices.GetRequiredService<ApplicationDbContext>();

        // 1. Determine if it's a controlled business error
        if (exception is CustomAppException customEx)
        {
            errorCode = customEx.ErrorCode;
            statusCode = StatusCodes.Status400BadRequest;
        }

        //TODO: Use JWT later
        // 2. Extract UserId if the user is authenticated
        int? userId = null;
        var userIdClaim = httpContext.User.FindFirst("UserId")?.Value;
        if (int.TryParse(userIdClaim, out int parsedUserId))
        {
            userId = parsedUserId;
        }

        // 3. Save the error to the database
        var errorLog = new ErrorLog
        {
            IncidentNumber = incidentNumber,
            OriginLayer = "API",
            MainObject = httpContext.Request.Path,
            MethodName = httpContext.Request.Method,
            Description = exception.InnerException?.Message,
            ErrorMessage = exception.Message,
            UserId = userId
            // ErrorDate is auto-generated by the entity
        };

        dbContext.ErrorLogs.Add(errorLog);
        await dbContext.SaveChangesAsync(cancellationToken);

        // 4. Log to console for local debugging
        logger.LogError(exception, "An error occurred. Incident Number: {IncidentNumber}", incidentNumber);

        // 5. Construct the standardized JSON response
        var problemDetails = new ProblemDetails
        {
            Status = statusCode,
            Title = exception is CustomAppException ? "Business Rule Violation" : "Internal Server Error",
            Detail = exception is CustomAppException ? exception.Message : "An unexpected error occurred. Please contact support.",
            Instance = httpContext.Request.Path
        };

        // Add the custom properties for frontend's i18n translation
        problemDetails.Extensions.Add("errorCode", errorCode);
        problemDetails.Extensions.Add("incidentNumber", incidentNumber);

        httpContext.Response.StatusCode = statusCode;
        await httpContext.Response.WriteAsJsonAsync(problemDetails, cancellationToken);

        return true; // Indicates the exception was successfully handled
    }
}